#!/bin/bash
################################################################################
# Logging functions
INFO(){ echo -n "INFO: "; echo "$@" ;}
WARN(){ echo -n "WARN: "; echo "$@" ;}
ERRO(){ echo -n "ERRO: "; echo -n "$@" ; echo " Abort!"; exit 1;}

################################################################################
# Check some deps
bin_exist(){
    if command -v "$1" &> /dev/null; then
        INFO "INFO: $1 checked"
    else
        ERRO "Missing ${1}!"
    fi
}

bin_exist wine
bin_exist winetricks

################################################################################
INFO "Last tested version: wine-1.9.23"

################################################################################
# Some vars
export WINEPREFIX WINEARCH
export PREFIXCOMMAND TMP
export LOL_OpenGL
export LOL_LAUNCHER_NAME LOL_INSTALL_PATH LOL_LAUNCHER_PATH
export LOL_RUN_LOG

WINEARCH=win32
WINEPREFIX="$HOME/.local/share/leagueoflegends"
PREFIXCOMMAND=""
LOL_OpenGL=2
LOL_RUN_LOG="$WINEPREFIX/wine_lol.log"
LOL_LAUNCHER_NAME="lol.launcher.exe"
LOL_INSTALL_PATH="$WINEPREFIX/drive_c/LoL/"

TMP="$(mktemp -u)"
################################################################################
# Initialization
CONF=/etc/leagueoflegends.conf
[ ! -f "$CONF" ] && ERRO "Missing: ${CONF}"
INFO "Reading Config"
# shellcheck source=leagueoflegends.conf
source "$CONF"

echo ---
INFO "Check: $WINEPREFIX"
if [ ! -d "$WINEPREFIX" ]; then
    INFO "Wine prefix not exist"
    INFO "So try recreate it"

    wineboot &> /dev/null

    INFO "Make user dirs isolated"
    find -H "$WINEPREFIX/drive_c/users/" -type l -delete

    INFO "Created: $WINEPREFIX"
fi

echo ---
INFO "Check: if configured"
REQ_MOD=( corefonts vcrun2005 vcrun2008 vcrun2015 d3dx9 )
for mod in "${REQ_MOD[@]}"; do
    if ! grep -q "$mod" "$WINEPREFIX/winetricks.log"; then
        winetricks -q "$mod" || ERRO "Something went wrong!"
    fi
done

rm_w(){ [ -f "$1" ] && rm "$1"; }

echo ---
reinstall(){
    for file in /opt/leagueoflegends/*.exe; do
        install -Dm644 "$file" "$LOL_INSTALL_PATH/$(basename "$file")" || ERRO "Something went wrong!"
    done
    for file in /opt/leagueoflegends/RADS/system/*; do
        install -Dm644 "$file" "$LOL_INSTALL_PATH/RADS/system/$(basename "$file")" || ERRO "Something went wrong!"
    done
}
INFO "Check if launcher installed"
if [ ! -d "$LOL_INSTALL_PATH" ]; then
    INFO "League of Legends not found at: $LOL_INSTALL_PATH"
    INFO "Try found any launcher"
    find -H "$WINEPREFIX/drive_c/" -name "$LOL_LAUNCHER_NAME" > "$TMP"
    read -r LOL_LAUNCHER_PATH < "$TMP"
    rm_w "$TMP"

    if [ -f "$LOL_LAUNCHER_PATH" ]; then
        INFO "Find another League of Legends launcher, move it to $LOL_INSTALL_PATH"
        dirname "$LOL_LAUNCHER_PATH" > "$TMP"
        read -r LOL_DIR < "$TMP"
        rm_w "$TMP"
        mv -v "$LOL_DIR/" "$LOL_INSTALL_PATH/"
    else
        INFO "League of Legends not found at $WINEPREFIX/drive_c/"
        INFO "So reinstall it"
        # Install Tiny Launcher
        reinstall
    fi
else
    INFO "League of Legends found at: $LOL_INSTALL_PATH"
fi

echo ---
INFO "Initialization Finished"

dos2unix(){ sed $'s/\r$//'; }
unix2dos(){ sed $'s/$/\r/'; }

LOL_game_cfg=$LOL_INSTALL_PATH/Config/game.cfg
if [ ! -f "$LOL_game_cfg" ]; then
    INFO "Can't find: $LOL_game_cfg"
    INFO "Ignore OpenGL setting"
    LOL_OpenGL=2
fi

case "$LOL_OpenGL" in
    0|1) dos2unix > "$TMP" < "$LOL_game_cfg" ;;
esac

case "$LOL_OpenGL" in
    0)
        if grep -q x3d_platform=1 "$LOL_game_cfg"; then
            sed -i 's/x3d_platform=1//g' "$TMP"
            unix2dos > "$LOL_game_cfg" < "$TMP"
            INFO "Disable OpenGL in game.cfg"
        fi
    ;;
    1)
        if ! grep -q x3d_platform=1 "$LOL_game_cfg"; then
            sed -i 's/\[General\]/\[General\]\n x3d_platform=1/g' "$TMP"
            unix2dos > "$LOL_game_cfg" < "$TMP"
            INFO "Enable OpenGL in game.cfg"
        fi
    ;;
esac

rm_w "$TMP"

LOL_RUN(){
    echo ---
    winepath -w "$LOL_INSTALL_PATH/$LOL_LAUNCHER_NAME" > "$TMP" 2> /dev/null
    read -r WIN_PATH < "$TMP"
    rm_w "$TMP"

    INFO "LoL Launcher path: $LOL_INSTALL_PATH/$LOL_LAUNCHER_NAME"
    INFO "Run: $LOL_LAUNCHER_NAME" | tee -a "$LOL_RUN_LOG"
    INFO "Wine run log: $LOL_RUN_LOG"
    $PREFIXCOMMAND wine "$WIN_PATH" $LOL_LAUNCHER_ARGS &>> "$LOL_RUN_LOG"
}

if [ -z "$1" ]; then
    LOL_RUN
else
    help(){
        echo "$0 <no args>  - launch lol"
        echo "$0 winecfg    - run winecfg in lol prefix"
        echo "$0 wineserver <args> - -k for killing all processes"
        echo "$0 reinstall  - reinstall lol launcher bins"
        echo "$0 beta       - launch lol beta client"
    }
    case "$1" in
        winecfg)
            winecfg
            { echo ---; echo "winecfg" ; echo ---; } &>> "$LOL_RUN_LOG" ;;
        wineserver)
            shift; wineserver "$@"
            { echo ---; echo "wineserver" "$@"; echo ---; } &>> "$LOL_RUN_LOG"
        ;;
        reinstall)
            reinstall
            { echo ---; echo "reinstall"; echo ---; } &>> "$LOL_RUN_LOG" ;;
        beta)
            LOL_LAUNCHER_NAME="LeagueClient.exe" LOL_LAUNCHER_ARGS="--no-sandbox"
            LOL_RUN
        ;;
        *) help ;;
    esac
fi
