#!/bin/bash
set -e

############################################################
## Logging functions
############################################################
INFO() { echo "INFO: $*"; }
WARN() { echo "WARN: $*"; }
ERRO() { echo "ERRO: $*"; exit 1; }

############################################################
## Ask question to user
############################################################
function askQ () {
  count=1
  first_arg="$2"
  echo
  echo "    $1"
  for var in "${@:2}"
  do
    echo "    #$count - $2"
    ((count++))
    shift
  done
  echo
}

############################################################
## Check dependencies
############################################################
deps=("wine" "wineboot" "winetricks" "winepath" "winecfg" "wineserver" "wget")
check_dep() { command -v "$1" >/dev/null 2>&1 || ERRO "Missing $1"; }
for dep in ${deps[@]}; do
    check_dep "$dep"
done

############################################################
## Preset default variable values
############################################################
export CONF="/etc/leagueoflegends.conf"
export USER_CONF="$HOME/.config/leagueoflegends.conf"
export REGFILE="/usr/share/doc/leagueoflegends/leagueoflegends.reg"
export CACHE_DIR="$HOME/.cache/leagueoflegends"
export LOL_CLIENT_BIN="LeagueClient.exe"
export WINEARCH=win64
export WINEDLLOVERRIDES="msvcp140=n,b"
export WINE_REQ_MOD=("d3dx9" "corefonts" "vcrun2017")
export BASE_DIR="$HOME/.local/share/leagueoflegends"
export WINEPREFIX="$BASE_DIR/wine.$WINEARCH"
export INSTALL_PATH="$BASE_DIR/LOL"
export CLIENT_PATH="$(find "$INSTALL_PATH" -name "$LOL_CLIENT_BIN" 2>/dev/null \
                    | sort | head -n1)"
export PREFIXCOMMAND
export MESA_GLTHREAD=true
export __GL_THREADED_OPTIMIZATIONS=0

############################################################
## Load configuration files
############################################################
source "$CONF" >/dev/null 2>&1 || ERRO "Missing $CONF"
[ -f "$USER_CONF" ] && source "$USER_CONF"

############################################################
## Check arguments
############################################################
case "$1" in
    launch)
        [ -z "$CLIENT_PATH" ] && ERRO "Game is not properly installed"
        CLIENT_PATH="$(winepath -w "$CLIENT_PATH")"
        INFO "Starting game"
        $PREFIXCOMMAND wine "$CLIENT_PATH"
        exit 0
        ;;
    install) : ;;
    uninstall)
        rm -rf "$USER_CONF" "$CACHE_DIR" "$BASE_DIR" "$WINEPREFIX" \
            "$INSTALL_PATH"
        exit 0
        ;;
    cleanup_logs)
        INFO "Removing log files"
        [ -d "$BASE_DIR" ] && {
            find -H "$BASE_DIR" -name "*.log" -delete -print
            [ -d "$INSTALL_PATH" ] && {
                find -H "$INSTALL_PATH" -name "*.log?" -delete -print
                [ -d "$INSTALL_PATH/Logs" ] && {
                    find -H "$INSTALL_PATH/Logs" -type f -delete -print
                    find -H "$INSTALL_PATH/Logs" -empty -delete -print
                }
            }
        }
        exit 0
        ;;
    winecfg|wineserver|winetricks)
        ARG="$1"; shift; exec "$ARG" "$@"
        ;;
    make_wineprefix|regen_wineprefix) : ;;
    *)
        echo "League of Legends - helper program"
        echo "Usage: $0 <command>"
        echo "Commands:"
        echo "    launch            - Launch LoL"
        echo "    install           - Install LoL"
        echo "    uninstall         - Uninstall LoL"
        echo "    cleanup_logs      - Remove log files"
        echo "    winecfg           - Run winecfg with WINEPREFIX"
        echo "    wineserver [...]  - Run wineserver with WINEPREFIX"
        echo "    winetricks [...]  - Run winetricks with WINEPREFIX"
        echo "    make_wineprefix   - Create WINEPREFIX only"
        echo "    regen_wineprefix  - Backup and recreate WINEPREFIX"
        exit 1
        ;;
esac

############################################################
## Create directories if needed
############################################################
[ ! -d "$BASE_DIR" ] && {
    INFO "Creating directory $BASE_DIR"
    mkdir -p "$BASE_DIR"
}
[ ! -d "$CACHE_DIR" ] && {
    INFO "Creating directory $CACHE_DIR"
    mkdir -p "$CACHE_DIR"
}
[ ! -d "$INSTALL_PATH" ] && {
    INFO "Creating directory $INSTALL_PATH"
    mkdir -p "$INSTALL_PATH"
}
[ ! -d "$WINEPREFIX" ] && {
    INFO "Creating and initializing $WINEPREFIX"
    env WINEDLLOVERRIDES="mscoree,mshtml=" wineboot -i >/dev/null 2>&1
}
INFO "Latest tested version: wine-3.21"
INFO "Your version: $(wine --version)"

############################################################
## Prepare the WINE environment
############################################################
if [ ! -f "$WINEPREFIX/winetricks.log" ]; then
    INFO "Installing verbs via winetricks"
    winetricks -q --optout "${WINE_REQ_MOD[@]}" \
        || ERRO "Failed to install required modules via winetricks"
fi
for link in "$WINEPREFIX/dosdevices"/*; do
    [[ "$link" =~ 'c:' ]] && continue # For default link to ../drive_c
    [[ "$link" =~ 'x:' ]] && continue # For link to LoL path
    [[ "$link" =~ 'z:' ]] && continue # For default link to /
    INFO "Removing unnecessary device $link"
    rm -v "$link"
done
INFO "Linking device x: to $INSTALL_PATH"
ln -Tfsr "$INSTALL_PATH" "$WINEPREFIX/dosdevices/x:"
INFO "Modifying WINE registry"
wine regedit "$REGFILE"

############################################################
## make_wineprefix ends here
############################################################
[ "$1" == "make_wineprefix" ] && exit 0

############################################################
## Install League of Legends
############################################################
askQ "Select your region" "North America" "EU West" "EU Nordic & East" "Latin America North" "Latin America South" "Brazil" "Turkey" "Russia" "Japan" "Oceania" "Republic of Korea"
read -p "    #: " answer

case "${answer}" in
    1)
        # North America
        export LANG_CODE="NA"
        ;;
    2)
        # EU West
        export LANG_CODE="EUW"
        ;;
    3)
        # EU Nordic & East
        export LANG_CODE="EUNE"
        ;;
    4)
        # Latin America North
        export LANG_CODE="LA1"
        ;;
    5)
        # Latin America South
        export LANG_CODE="LA2"
        ;;
    6)
        # Brazil
        export LANG_CODE="BR"
        ;;
    7)
        # Turkey
        export LANG_CODE="TR"
        ;;
    8)
        # Russia
        export LANG_CODE="RU"
        ;;
    9)
        # Japan
        export LANG_CODE="JP"
        ;;
    10)
        # Oceania
        export LANG_CODE="OC1"
        ;;
    11)
        # Republic of Korea
        export LANG_CODE="KR"
        ;;
esac

export INSTALLER="$CACHE_DIR/LoL_installer_$LANG_CODE.exe"

if [ "$LANG_CODE" = "KR" ]; then
    export INSTALLER_URL="https://riotgamespatcher-a.akamaihd.net/KR_CBT/installer/deploy/League of Legends installer KR.exe"
else
    export INSTALLER_URL="https://riotgamespatcher-a.akamaihd.net/releases/live/installer/deploy/League%20of%20Legends%20installer%20$LANG_CODE.exe"
fi

INFO "Downloading installer"
wget -cO "$INSTALLER" "$INSTALLER_URL"
[ -z "$CLIENT_PATH" ] && {
    INFO "Installing League of Legends"
    wine "$INSTALLER" \
        --license_agreement 1 \
        --mode unattended \
        --installdir "$INSTALL_PATH"
}
echo
INFO "League of Legends installed!"
INFO
INFO "The game is installed in $INSTALL_PATH"
INFO "with WINEPREFIX=$WINEPREFIX"
echo

############################################################
## regen_wineprefix ends here
############################################################
[ "$1" == "regen_wineprefix" ] && {
    [ -d "${WINEPREFIX}.backup" ] && \
        ERRO "Backup of ${WINEPREFIX} already exist"
    INFO "Backup prefix: ${WINEPREFIX}.backup"
    mv "${WINEPREFIX}" "${WINEPREFIX}.backup"
    INFO "Recreating wineprefix"
    exec "$0" make_wineprefix
}

# vim: set ts=4 sw=4 et:
